#!/bin/sh
if command -v rofi >/dev/null 2>&1; then
  themefile=~/.cache/wal/colors-rofi-dark.rasi
  if [ -f "$themefile" ]; then
    rofi -dmenu -i -theme "$themefile" "$@"
  else
    rofi -dmenu -i "$@"
  fi
elif command -v dmenu >/dev/null 2>&1; then
  dmenu "$@"
else
  notify-send "no launcher found"
fi
