#!/bin/sh

# General variables
export LC_TIME="en_US.UTF-8"
export LANG="en_US.UTF-8"
export VISUAL="vim"
export TERMINAL="alacritty"
export EDITOR="emacsclient -nw -a ''"
export READER="zathura"

# Setup PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:$HOME/.local/bin

[ -d ${HOME}/.emacs.d/bin ] && export PATH=$PATH:$HOME/.emacs.d/bin
[ -d ${HOME}/.config/emacs/bin ] && export PATH=$PATH:$HOME/.config/emacs/bin

[ -d "/opt/asdf-vm" ] && export ASDF_DATA_DIR="/opt/asdf-vm" || export ASDF_DATA_DIR="$HOME/.asdf"
[ -f "$ASDF_DATA_DIR/asdf.sh" ] && source "$ASDF_DATA_DIR/asdf.sh"

command -v guix 1>/dev/null \
	&& export GUIX_PROFILE="${HOME}/.config/guix/current" \
        && test -f "$GUIX_PROFILE/etc/profile" \
	&& . "$GUIX_PROFILE/etc/profile"

test -e $HOME/.nix-profile/etc/profile.d/nix.sh \
	&& source $HOME/.nix-profile/etc/profile.d/nix.sh

command -v flatpak 1>/dev/null \
	&& export PATH="$PATH:/var/lib/flatpak/exports/bin:${HOME}/.local/share/flatpak/exports/bin"

test -f "$HOME/.config/shell/profile.local" && source ~/.config/shell/profile.local
