[
  {
    "battery": {
      "format": "{capacity}% {icon}",
      "format-icons": [
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "clock": {
      "format": "{:%Y-%m-%d %H:%M}"
    },

    "layer": "top",
    "modules-center": [
        "niri/window"
    ],
    "modules-left": [
        "niri/workspaces",
    ],
    "modules-right": [
      "sway/language",
      "pulseaudio",
      "network",
      "battery",
      "clock",
      "tray"
    ],
     "niri/workspaces": {
        "format": "{name}",
    },
    "niri/window": {
    	"format": "  {title}",
    	"rewrite": {}
    },
    "network": {
      "format-disconnected": "Disconnected",
      "format-ethernet": "Wired",
      "format-wifi": "{essid}"
    },
    "position": "top",
    "pulseaudio": {
      "format": "{volume}% {icon}",
      "format-icons": {
        "default": [
          "",
          "",
          ""
        ]
      },
      "format-muted": "Muted",
      "on-click": "/nix/store/xv0lhca90pwf70as12jrn3q9hv3b9x9z-pavucontrol-6.2/bin/pavucontrol"
    }
  }
]
