[
  {
    "battery": {
      "format": "{capacity}% {icon}",
      "format-icons": [
        "",
        "",
        "",
        "",
        ""
      ]
    },
    "clock": {
      "format": "{:%Y-%m-%d %H:%M}"
    },

    "layer": "top",
    "modules-center": [
        "dwl/window"
    ],
    "modules-left": [
        "ext/workspaces"
    ],
    "modules-right": [
      "pulseaudio",
      "network",
      "battery",
      "clock",
      "tray"
    ],
    "ext/workspaces": {
      "format": "{icon}",
      "ignore-hidden": false,
      "on-click": "activate",
      "on-click-right": "deactivate",
      "sort-by-id": true
    },
    "dwl/window": {
      "format": "{layout}  {title}"
    },
    "network": {
      "format-disconnected": "Disconnected",
      "format-ethernet": "Wired",
      "format-wifi": "{essid}"
    },
    "position": "top",
    "pulseaudio": {
      "format": "{volume}% {icon}",
      "format-icons": {
        "default": [
          "",
          "",
          ""
        ]
      },
      "format-muted": "Muted",
      "on-click": "/nix/store/xv0lhca90pwf70as12jrn3q9hv3b9x9z-pavucontrol-6.2/bin/pavucontrol"
    }
  }
]
