#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

# Spread desktops across monitors
desktop=1
monitors_connected=$(bspc query -M | wc -l)
per_monitor=$(( 10 / monitors_connected ))
for monitor in $(bspc query -M | tac); do
  bspc monitor "$monitor" -d $(seq "$desktop" $(( desktop + per_monitor - 1)))
  desktop=$(( desktop + per_monitor ))
done

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config directional_focus_tightness low

bspc config border_width 3
bspc config window_gap 0

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config bottom_monocle_padding -23

xsetroot -cursor_name left_ptr
bspc config pointer_follows_focus false

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Zoom state=floating

POLYBAR_PATH="$HOME/.config/polybar/start.sh"
test -f "$POLYBAR_PATH" && ("$POLYBAR_PATH" &) || notify-send "Could not start polybar"

bspc config bottom_padding 0
