#!/bin/zsh

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/' -e 's/HEAD detached from //'
}

setopt PROMPT_SUBST

test -f ~/.cache/wal/colors.sh && source ~/.cache/wal/colors.sh
PS1='%F{244}%n %F{180}%1~$(parse_git_branch) %F{244}%(!.#.$)%f '
RPROMPT='%F{244}$(hostname)%f'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
